### ISSUE TITLE
Europe PMC dataset parameter fulltext removed

### ISSUE THREAD

**Issue by njahn82** [articlemetrics/lagotto#245]
Please be aware that Europe PMC has recently removed the `dataset` parameter which Lagotto uses to search Europe PMC.

**Comment by mfenner** [comment]
Thank you. It should therefore be http://www.ebi.ac.uk/europepmc/webservices/rest/search/query=https://github.com/najoshi/sickle&format=json&resultType=lite instead of http://www.ebi.ac.uk/europepmc/webservices/rest/search/query=https://github.com/najoshi/sickle&dataset=fulltext&format=json&resultType=lite. It seems that the dataset parameter is simply ignored.

Here is the documentation: http://europepmc.org/restfulwebservice#search
