### ISSUE TITLE
error attempting to run migrations for Lagotto 4.0

### ISSUE THREAD

**Issue by lsh-0** [articlemetrics/lagotto#304]
$ RAILS_ENV=production rake db:migrate
    == 20150325124452 ChangeMetricsDefaultToZero: migrating =======================
    -- change_column(:retrieval_statuses, :pdf, :integer, {:default=>0, :null=>false})
    rake aborted!
    StandardError: An error has occurred, all later migrations canceled:

    Mysql2::Error: Data truncated for column 'pdf' at row 1: ALTER TABLE `retrieval_statuses` CHANGE `pdf` `pdf` int(11) DEFAULT 0 NOT NULL/var/lib/gems/2.1.0/gems/rack-mini-profiler-0.9.3/lib/patches/db/mysql2.rb:20:in `query'

I've taken a look at the values in the `retrieval_statuses.pdf` column and it's nothing but `null`s. Not sure if that was part of a migration process or our original data. Updating the values from `null` to `0` and re-running the migration gets the same result but for the `html` column. And then again for the `readers`, `comments`, and `likes` columns. 

got the same error again at `api_responses.pdf` and gave up.

**Comment by mfenner** [comment]
Since release 3.18, Lagotto is using data migrations to avoid this kind of problem. They run automatically if you use capistrano to upgrade, you need to run `RAILS_ENV=production rake data:migrate` otherwise. The relevant data migration for this particular case is https://github.com/articlemetrics/lagotto/blob/4-0-stable/db/data_migrate/20150325114452_change_metrics_default_to_zero.rb, more info about data migrations at https://github.com/jasonfb/nondestructive_migrations. I will update the documentation to make this clearer, was assuming an upgrade with capistrano.

**Comment by lsh-0** [comment]
Running `data:migrate` before `db:migate` appears to work, thanks Martin.
