### ISSUE TITLE
add Downloaded category to Sources list

### ISSUE THREAD

**Issue by mbjones** [articlemetrics/lagotto#352]
The current Sources UI shows categories for 'Saved', 'Discussed', and 'Cited'. I proposed that there should be a 'Downloaded' category for the DLM site, which would include the DataONE repository network as one source of these statistics.  Or would you consider that one of the types of 'Saved' statistics?

**Comment by mfenner** [comment]
The built-in groups for sources are the following:

* saved
* discussed
* cited
* viewed
* other

The following paper goes a little bit into the background for those categories: http://doi.org/10.3789/isqv25no2.2013.04. We are using the **viewed** group for usage stats in other places, and the usage stats from DataONE seem to also fit into this group. You can see in the DLM API (http://dlm.plos.org/api/groups) that the `viewed` group is currently empty. 

Something we can discuss is whether `viewed` is the right name to describe this group/category, but that is something I would rather have the NISO Working Group on Definitions and Use Cases (http://www.niso.org/topics/tl/altmetrics_initiative/) have decide - so that we use consistent language across services and projects. I can bring up the topic of categories/groups in that NISO group.
